# Define the name for the stack
name: backend-api-stack

services:
  # Backend API service configuration
  backend-api:
    image: abid127/backend-api
    container_name: backend-api-container  # Name of the container
    depends_on: mongodb
    environment:
      - MONGO_URI=mongodb://root:pass-123@mongodb:27017/book-store?authSource=admin  # MongoDB connection URI
      - PORT=3001  # Port to run the backend API
    ports:
      - '4000:3001'  # Map the container's port 3001 to the host machine's port 3001
    depends_on:
      - mongodb  # Ensure MongoDB starts before the backend API
   # networks:
     # - backend-api-network  # Connect the service to the defined network

  # MongoDB service configuration
  mongodb:
    container_name: mongodb  # Name of the container
    image: mongo:latest  # Use the latest MongoDB image from Docker Hub
    restart: always  # Automatically restart MongoDB container if it stops
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # Root username for MongoDB
      - MONGO_INITDB_ROOT_PASSWORD=pass-123  # Root password for MongoDB
      - MONGO_INITDB_DATABASE=book-store  # Initial database to create
    ports:
      - "27017:27017"  # Map the container's MongoDB port to the host's port 27017

  mongo-express:
    image: mongo-express
    depends_on: mongodb
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass-123
      ME_CONFIG_MONGODB_URL: mongodb://root:pass-123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
