#name: frontend-app-stack

# Define services
services:
  frontend-app:
    image: abid127/frontend-api
      args:
        VITE_API_URL: http://localhost:3001  # API URL for the frontend app
    container_name: frontend-app  # Set a custom name for the container
    ports:
      - '3001:80'  # Map port 3000 on the host to port 80 in the container
